### PR TITLE
Fix 'mix test --cover'

### PR DESCRIPTION
**Pull request by ericmj**
Without this change calling `mix test --cover` will crash.

### CODE REVIEW

**Comment by hunterboerner** [comment]
This still seems to be an issue.

**Comment by ericmj** [comment]
Works on my machine. What issue are you seeing?

**Comment by hunterboerner** [comment]
image

**Comment by ericmj** [comment]
It doesn't find excoveralls. Have you added it as a dependency? Is it in the test environment?

**Comment by hunterboerner** [comment]
Right... the readme says to use `only: :dev` but I needed `only: [:dev, :test]` Thanks. this is fixed now.

**Comment by ericmj** [comment]
The readme should be updated, I see no reason for it to run in :dev.

**Comment by hunterboerner** [comment]
@ericmj maybe for the `mix coveralls` commands?

**Comment by ericmj** [comment]
Ah, you're right.

On Sun, Mar 15, 2015 at 9:59 PM, Theron Boerner <notifications@github.com>
wrote:

> @ericmj <https://github.com/ericmj> maybe for the mix coveralls commands?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parroty/excoveralls/pull/8#issuecomment-81236936>.
>



-- 
Eric Meadows-Jönsson

**Comment by parroty** [comment]
Thanks. I made a quick fix to include `:test`. The intention for `:dev` was to easily use `mix coveralls` as @hunterboerner indicated (There's some weirdness, but not sure if behaviors should be modified).

**Pull request merged**
