### PR TITLE
Updated Semaphore variables

### LINKED ISSUE #179: Semaphore CI 2.0 uses different CI environment variables
The current Semaphore task supports only Semaphore's "classic" CI environment, whereas in 2.0 they changed up the environment variables:

https://docs.semaphoreci.com/article/12-environment-variables

`REVISION` -> `SEMAPHORE_GIT_SHA`
`BRANCH_NAME` -> `SEMAPHORE_GIT_BRANCH `
`SEMAPHORE_BUILD_NUMBER` -> `SEMAPHORE_JOB_ID `

I'm not sure if `PULL_REQUEST_NUMBER` hash changed or not, though—the documentation doesn't mention it at all.

### PR DESCRIPTION
**Pull request by gabrielrinaldi**
This should fix #179.

This is a breaking change for people who haven't migrated to the new Semaphore.

### CODE REVIEW

**Comment by parroty** [comment]
Thanks!
Do you have any insight/opinion regarding the breaking-change perspective? (just bump version to`v0.12.0` and note in changelog would be enough? or additional attention would be required?)

**Comment by gabrielrinaldi** [comment]
@parroty I am not familiar with how Semaphore is handling 1.0 vs 2.0 right now, but I know some people are still using 1.0. So it would be a braking change.

**Comment by parroty** [comment]
Thanks for the information. Removing the breaking change seems to require more work, and I'll be pushing the current code with different minor version.

**Comment by losvedir** [comment]
I've just been trying to update my apps' dependencies but we're still on Semaphore Classic, so it looks like we can no longer update `excoveralls`. Upgrading from Classic to 2 isn't really something in my control.

Is there a reason we couldn't just handle both versions? Something like:

```ex
def get_sha do
  System.get_env("REVISION") || System.get_env("SEMAPHORE_GIT_SHA")
end
```

instead of just replacing the old with the new? In addition, that would allow users like us to upgrade to Semaphore 2 sometime in the future without simultaneously breaking all our builds.

**Pull request merged**
