### PR TITLE
Add support for github actions

### PR DESCRIPTION
**Pull request by mijailr**
This add the ability to use with Github actions.

With:

    mix coveralls.github

Related with #202

### CODE REVIEW

**Comment by mijailr** [comment]
Do not merge, the test are passing but ii get this error on productio (sample)

    Failed to upload the report to 'https://coveralls.io' (reason: status_code = 422, body = {"message":"Couldn't find a repository matching this job.","error": true}

I think i have the job id correct, but there are something missing.

**Comment by mijailr** [comment]
We have it done!!! :tada: 

Please review and merge!

Here is an example using excoveralls with github actions: https://github.com/mijailr/actions_sample/

**Comment by parroty** [comment]
Thanks for the enhancement. Is it possible to squash the commits?

**Comment by mijailr** [comment]
Yes, squash and merge. No problem... i make many mistakes.

**Comment by mijailr** [comment]
Well better i close this and make a single commit.

**Pull request closed without merging**
