### PR TITLE
Add a task to upload coverage from gitlab

### PR DESCRIPTION
**Pull request by ggpasqualino**
Hi there, 
I see the example uses the native coverage of GitLab.
I would like to use coveralls though because of the parallel feature.
What do you think? Would it make sense to add that?

Cheers

### CODE REVIEW

**Comment by parroty** [comment]
Thanks for the PR. If it does not affect the existing behavior, it may make sense to add the capability, but could I request some description (or reference) regarding the usage? (or any sample would be helpful).

**Comment by ggpasqualino** [comment]
@parroty awesome :) 
I have made this demo repo to describe the usage https://gitlab.com/ggpasqualino/excoveralls-demo/

**Comment by parroty** [comment]
Thanks for providing example.
- Please let me ask how the token (`COVERALLS_REPO_TOKEN`) is being passed for your demo repository?
    - It's configured as part of GitHub CI settings? (I'm trying to fork the repository to my account and checking the behavior).
- Can I fork (or link the) demo repository to put the reference in the README?

**Comment by ggpasqualino** [comment]
> Thanks for providing example.
> 
> * Please let me ask how the token (`COVERALLS_REPO_TOKEN`) is being passed for your demo repository?
>   
>   * It's configured as part of GitHub CI settings? (I'm trying to fork the repository to my account and checking the behavior).

Yes, you can find the place to set it up under https://gitlab.com/ggpasqualino/excoveralls-demo/-/settings/ci_cd#Variables just replace my user with yours :)

> * Can I fork (or link the) demo repository to put the reference in the README?

Yes, for sure you may fork it and link it in the README

**Comment by parroty** [comment]
Thanks for the clarifications. I've updated the reference as https://gitlab.com/parroty/excoveralls-demo/ (also added small note about `COVERALLS_REPO_TOKEN` environment variable).

**Pull request merged**
