### PR TITLE
Add support for GitHub Actions.

### PR DESCRIPTION
**Pull request by scouten**
**NOT READY TO MERGE YET**.

### CODE REVIEW

**Comment by scouten** [comment]
@jclem: Would you look at https://github.com/parroty/excoveralls/pull/202/files#diff-fe45863ce5cc0baa87f72c6a67dbb861 and suggest appropriate environment variables? I did a dump of the env when running an action. (See https://github.com/scouten/github_coverage_sample/pull/1/checks?check_run_id=303367732.)

Thanks!

**Comment by scouten** [comment]
Closes #201.

**Comment by mijailr** [comment]
Any updates to this?

**Comment by scouten** [comment]
I am sad to say that I have abandoned this effort. IMHO the combination of APIs available via Coveralls and GitHub Actions does not have enough in common to allow the two to work together effectively. (To be clear, this is no fault of the *excoveralls* library.)

In the project I'm authoring, I have abandoned Coveralls in favor of CodeCov, which has a fairly nice integration with GitHub Actions that I was able to leverage.

For an example of how to make that transition, please see:

* https://github.com/elixir-git/xgit/pull/216 [switch from Coveralls to CodeCov]
* https://github.com/elixir-git/xgit/pull/215 [switch from Travis CI to GitHub Actions]

**Comment by scouten** [comment]
Just realized that I should have stated this: I continue to use the *excoveralls* library in my project. It is able to generate data that is consumable by CodeCov.

**Comment by mijailr** [comment]
Well, i will use the code you share to make it done. Adding the missing parts.

**Comment by mijailr** [comment]
@scouten i have it!!!! Please review the #206

**Comment by jclem** [comment]
Thanks for this @scouten and @mijailr! I apologize for my absence from this thread—combination of Actions GA work and holidays have kept me a little heads-down lately.

Y'all are crushing it though! Keep cc-ing me elsewhere and I'll keep up as much as I can.

**Pull request closed without merging**
