### PR TITLE
Add optional width to column to present filename

### PR DESCRIPTION
**Pull request by CaptChrisD**
Still leaves default to 40 columns but allows configuring.

This is important for umbrella projects where the filename can get to large for the default column width.

### CODE REVIEW

**Comment by CaptChrisD** [comment]
Sorry didn't mean to update the lock file

**Comment by parroty** [comment]
Thanks, it sounds nice!

**Comment by CaptChrisD** [comment]
Could you let me know when this will make it into a release on hex so we can get back on there instead of my fork?

**Comment by parroty** [comment]
I'll be pushing, but please allow one (or two) days.
I saw some warnings with latest elixir (though it's not related to this commit) and was trying to resolve (and timed up yesterday).

**Comment by CaptChrisD** [comment]
Not a problem. Just new to your project and didn't know if it was a quick release cycle or might be a while

**Pull request merged**
