### PR TITLE
Add HTMLCov style reports

### PR DESCRIPTION
**Pull request by erikreedstrom**
- added task for html report generation
- tests added for report generation
- updated mock lib to allow for context in mocked tests

### CODE REVIEW

**Comment by erikreedstrom** [comment]
Not sure why https://travis-ci.org/parroty/excoveralls/jobs/106358197 failed. Looks to be an issue with Travis posting to coveralls. Should pass, but I don't have the ability to rerun.

**Comment by parroty** [comment]
Thanks, please allow me some time to review, as its relatively large one. It might be on weekend.

**Comment by erikreedstrom** [comment]
No worries. There's likely room for improvement. Open for suggestions.

**Comment by parroty** [comment]
Sorry taking time, I'm just trying out. 
It's working great and the design seems quite nice too! Is there any base templates?

Some feedbacks are,
- How about having color on covered lines? (ex. green color). I can se line counts, but maybe good to have easier indicator to differentiate them from irrelevant lines.
- It's minor ones, but it seems some warnings are emitted (following).

```
lib/excoveralls/html.ex:135: warning: function print_string/2 is unused
...
lib/excoveralls/html.ex:6: warning: unused alias Local
```

**Comment by erikreedstrom** [comment]
Thanks for the feedback!

There is only this template currently, but it can be modified easily to add the green highlighting. Although this template followed the HTMLCov design, I thought I would add one that matches the Coveralls.io report style as well. Additionally, it should be easy enough to adjust the config to allow for fully custom templates if one desires.

I was rushing this change out so we could use it in-house; it looks like I missed the warnings. I'll clean up the code. ;)

**Comment by erikreedstrom** [comment]
- rebased on `upstream/master`
- removed code causing warnings
- added highlights for covered lines
- added ability for custom template path to be declared

The custom templates could use some work, but it at least provides the ability, even if not in an elegant way 😜

**Comment by parroty** [comment]
Thanks, great ones!

**Pull request merged**
